Print passing/failing tests + exit code to help debug.

diff --git a/.github/workflows/hitch.yml b/.github/workflows/hitch.yml
--- a/.github/workflows/hitch.yml
+++ b/.github/workflows/hitch.yml
@@ -60,7 +60,7 @@ jobs:
           ref: 1.7.3
           path: hitch
 
-      - name: Debug hitch configure
+      - name: Configure and build hitch
         run: |
             cd $GITHUB_WORKSPACE/hitch/
             patch -p1 < $GITHUB_WORKSPACE/osp/hitch/hitch_1.7.3.patch
@@ -85,12 +85,13 @@ jobs:
           export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/build-dir/lib:$LD_LIBRARY_PATH
           ldd src/hitch | grep wolfssl
 
+      # Note: Exit status 77 means a test was skipped, this is valid and expected.
       - name: Run hitch tests, skipping 13, 15 and 39
         working-directory: ./hitch/src/tests
         run: |
           export TESTDIR=`pwd`/; export PATH=$PATH:`pwd`/../:`pwd`/../util/:`pwd`; export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/build-dir/lib:$LD_LIBRARY_PATH
           for test in ./test*.sh; do
             if ! [[ "$test" = ./test13* ]] && ! [[ "$test" = ./test15* ]] && ! [[ "$test" = ./test39* ]]; then
-              $test
+              $test && echo "PASS: $test" || (ret=$?; if [[ $ret != 77 ]]; then echo "FAIL: $test (exit status: $ret)" && exit $ret; else echo "SKIP: $test"; fi)
             fi
           done
